### ISSUE TITLE
Move resolver configuration to catalog.

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/ermresolve#2]
I think it would make configuration and maintenance less error prone if the ability to resolve a table was indicated as an annotation on the table rather then in a separate config file.  

Also along these lines, it would be good to make sure that whenever we created a new catalog in a server, that the resolver was made aware so that IDs within that catalog were referable by their RIDS.

**Comment by karlcz** [comment]
I don't think the config can be in a catalog since the target catalog is specified by the config. I think the changes proposed for using the new ERMrest entity_rid API approach this problem from a different angle, avoiding the need for custom configuration for basic RID resolution scenarios.
